### ISSUE TITLE
Keep different data directory locations when working on different devices

### ISSUE THREAD

**Issue by siainbuletin** [PKM-er/obsidian-zotlit#218] opened 2023-10-13 06:34 UTC
I use Zotero both on my Macbook and my Windows PC, so the data directory location is wildly different (on my Windows PC it's even stored on a second hard drive, so not even close). The former has the files stored on `/users/<user>/Zotero` and the latter is on `D:/.../Syncing/Zotero`.

Every time I switch devices (between working on campus and at home) I have to also switch the location of the data directory in the settings of the plugin and then reload as well (in some cases). This is obviously cumbersome. It would be good if different locations for the data directory could be stored in the config file of the plugin (or in different iterations of the config, who knows).

**Comment by aidenlx** [comment] 2023-10-14 12:28
duplicate of #92

**Closed by aidenlx** 2023-10-14 12:28 UTC
