### ISSUE TITLE
date data only has year value AND there is no funtions for formating dates.

### ISSUE THREAD

**Issue by ertugruluyar-github** [PKM-er/obsidian-zotlit#204] opened 2023-10-08 09:58 UTC
![image](https://github.com/PKM-er/obsidian-zotlit/assets/70096810/b9a1f2fe-e496-4dbb-8bac-2f5f0aa27f77)

**Comment by aidenlx** [comment] 2023-10-08 10:17
Duplicate of #202, could you post the link to the literature that have broken date? （post the follow-up in #202)

**Closed** 2023-10-08 10:18 UTC
Labels: duplicate

**Comment by aidenlx** [comment] 2023-10-08 10:19
Oh and about formatting, you can use [moment](https://momentjs.com) to do date and time formatting

**Comment by ertugruluyar-github** [comment] 2023-10-08 11:06
> Oh and about formatting, you can use [moment](https://momentjs.com) to do date and time formatting

Thanks.

**Comment by ParkerRobb** [comment] 2024-01-17 02:38
See #265 for a workaround
