### ISSUE TITLE
better-bibtext-search.sqlite not load

### ISSUE THREAD

**Issue by aiyolo** [PKM-er/obsidian-zotlit#243] opened 2023-10-29 16:03 UTC
I installed  better-bibtext in zotero, but the plugin only generates better-bibtext.sqlite, and the better-bibtext-search.sqlite is missing.

![image](https://github.com/PKM-er/obsidian-zotlit/assets/12464091/621df148-d903-44fa-a546-f78a5f4a0c64)
zotero: 7.0.0-beta.47+f012a348a (64-bit)
obsidian: v1.4.16

how to configure it?

**Comment by FeralFlora** [comment] 2023-10-29 21:24
This is a duplicate of #236. Follow the progress on solving this there.

**Comment by aidenlx** [comment] 2023-10-30 19:32
should be fixed in v1.1.3

**Closed by aidenlx** 2023-10-30 19:32 UTC
